name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1.1.0
      - uses: fish-actions/fisher@v1
        with:
          plugins: jorgebucaran/fishtape ilancosman/clownfish $GITHUB_WORKSPACE
      - name: Run full test suite
        run: fishtape tests/*.fish
        shell: fish {0}
        timeout-minutes: 3
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - uses: fish-actions/syntax-check@v1
  # check Fish format
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - uses: fish-actions/format-check@v1
